services:
  app:
    container_name: app.${APP_NAME}
    build:
      context: .
      dockerfile: .docker/go/Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
      - "${DIAG_PORT}:${DIAG_PORT}"
    environment:
      - DB_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_DATABASE}?sslmode=disable
      - API_PORT=${API_PORT}
      - DIAG_PORT=${DIAG_PORT}
      - HTTP_TIMEOUT=${HTTP_TIMEOUT}
      - IDLE_TIMEOUT=${IDLE_TIMEOUT}
      - SHUTDOWN_TIMEOUT=${SHUTDOWN_TIMEOUT}
    depends_on:
      - db
      - dbmate
    networks:
      - app

  db:
    container_name: db.${APP_NAME}
    image: postgres:17
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
    networks:
      - app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}" ]
      interval: 1s
      timeout: 2s
      retries: 5
    restart: unless-stopped

  dbmate:
    container_name: dbmate.${APP_NAME}
    image: amacneil/dbmate:2.28
    entrypoint: ["dbmate", "up"]
    environment:
      - DATABASE_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_DATABASE}?sslmode=disable
    volumes:
      - ./db:/db
    depends_on:
      - db
    networks:
      - app

volumes:
  pg_data:

networks:
  app:
    driver: bridge